fileVersion: 1
id: "2"
mappingDefinitions:
  DESTINATION:
    database: BEN_EDW
    schema: SCHEMA_3
  SOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: Preview.staging environment
type: Environment
